# Generated by Django 4.0.6 on 2022-08-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.TextField()),
                ('customer_surname', models.TextField()),
                ('customer_dni', models.TextField(db_column='customer_DNI', unique=True)),
                ('dob', models.TextField(blank=True, null=True)),
                ('branch_id', models.IntegerField()),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.TextField()),
                ('numero', models.IntegerField()),
                ('ciudad', models.TextField()),
                ('provincia', models.TextField()),
                ('pais', models.TextField()),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('id_empleado', models.IntegerField(blank=True, null=True)),
                ('id_sucursal', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'direcciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.TextField()),
                ('employee_surname', models.TextField()),
                ('employee_hire_date', models.TextField()),
                ('employee_dni', models.TextField(db_column='employee_DNI')),
                ('branch_id', models.IntegerField()),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RestriccionesTipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipo_cliente', models.IntegerField(unique=True)),
                ('limite_extraccion_diario', models.DecimalField(decimal_places=5, max_digits=10)),
                ('limite_transferencia_recibida', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('monto', models.DecimalField(decimal_places=5, max_digits=10)),
                ('costo_transferencias', models.DecimalField(decimal_places=5, max_digits=10)),
                ('saldo_descubierto_disponible', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
            options={
                'db_table': 'restricciones_tipo_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_number', models.BinaryField()),
                ('branch_name', models.TextField()),
                ('branch_address_id', models.IntegerField()),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCombinacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'tipo_combinacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposCliente',
            fields=[
                ('id_tipo_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
                ('max_chequeras', models.IntegerField()),
                ('max_tarjetas_credito', models.IntegerField()),
                ('max_tarjetas_debito', models.IntegerField()),
            ],
            options={
                'db_table': 'tipos_cliente',
                'managed': False,
            },
        ),
    ]
