# Generated by Django 4.0.6 on 2022-08-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcasTarjeta',
            fields=[
                ('id_marca_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.TextField()),
            ],
            options={
                'db_table': 'marcas_tarjeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('id_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('id_marca_tarjeta', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('numero', models.IntegerField(unique=True)),
                ('cvv', models.IntegerField(db_column='CVV')),
                ('fecha_otorgamiento', models.TextField()),
                ('fecha_expiracion', models.TextField()),
            ],
            options={
                'db_table': 'tarjetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTarjeta',
            fields=[
                ('id_tipo_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
            ],
            options={
                'db_table': 'tipo_tarjeta',
                'managed': False,
            },
        ),
    ]
