-- TODO:
-- 1.  Crear una vista con las columnas id, numero sucursal, nombre, apellido, 
--     DNI y edad de la tabla cliente
--     o Mostrar las columnas de los clientes, ordenadas por el DNI de menor
--         a mayor y cuya edad sea superior a 40 años
--     o Mostrar todos los clientes que se llaman “Anne” o “Tyler” ordenados
--         por edad de menor a mayor
-- 2. Insertar 5 nuevos clientes (estan en la consigna) en la base de datos y 
--      verificar que se haya realizado con éxito la inserción
-- 3. Actualizar 5 clientes recientemente agregados en la base de datos dado que
-- hubo un error en el JSON que traía la información, la sucursal de todos es la 10
-- 4. Eliminar el registro correspondiente a “Noel David” realizando la selección
-- por el nombre y apellido
-- 5. Consultar sobre cuál es el tipo de préstamo de mayor importe